import { TranslationEngine } from './engine.js';
const languages=[['en','English'],['ja','日本語'],['es','Español'],['fr','Français'],['de','Deutsch'],['ko','한국어'],['zh','中文'],['pt','Português'],['vi','Tiếng Việt'],['ru','Русский']];
const tags={en:'en-US',ja:'ja-JP',zh:'zh-CN'};
const $=id=>document.getElementById(id), bridge=window.VoiceBridgeAndroid;
let session=null, generation=0, first='en', second='ja', speaker='en';
const name=code=>code==='auto'?'Auto · English / 日本語':languages.find(([c])=>c===code)?.[1]||code;
for(const id of ['first','second'])for(const [value,text] of languages){const option=document.createElement('option');option.value=value;option.textContent=text;$(id).append(option);}
$('first').value=first;$('second').value=second;
function note(message=''){ $('error').textContent=message;$('error').hidden=!message; }
function status(message){$('status').textContent=message;}
function render(){if($('speaker-auto')){$('speaker-auto').hidden=!bridge?.autoAvailable||!([first,second].includes('en')&&[first,second].includes('ja'));$('speaker-auto').setAttribute('aria-pressed',String(speaker==='auto'));$('speaker-auto').disabled=false;}const active=!!session;$('first').disabled=active;$('second').disabled=active;$('start').textContent=active?'Stop conversation':'Start conversation';$('start').disabled=!active&&first===second;$('speaker-first').textContent=first==='ja'?'日本語で話す':name(first)+' speaker';$('speaker-second').textContent=second==='ja'?'日本語で話す':name(second)+' speaker';for(const [id,code]of[['speaker-first',first],['speaker-second',second]]){$(id).setAttribute('aria-pressed',String(speaker===code));$(id).disabled=false;} $('finish').hidden=!active||session.phase!=='listening'||session.typed;if($('translate-text')){$('translate-text').disabled=active||first===second;$('typed-text').disabled=active;}}
function stop(message='Stopped · last exchange stays here'){const old=session;session=null;generation++;if(old){clearTimeout(old.timer);clearTimeout(old.playbackTimer);old.engine.close();bridge?.cancel();} $('level').value=0;$('progress').hidden=true;status(message);render();}
function progress(s,p){if(session!==s)return;$('progress').hidden=false;$('progress-text').textContent=p.message;$('download').hidden=typeof p.progress!=='number';if(typeof p.progress==='number')$('download').value=p.progress;}
function listen(s){if(session!==s)return;s.phase='listening';s.language=speaker;$('progress').hidden=true;$('level').value=0;status('Opening microphone · '+name(speaker));render();bridge.start(tags[speaker]||speaker,s.id);}
function rearm(s){if(session!==s)return;if(s.typed){stop('Translated · type another phrase or start a conversation');return;}clearTimeout(s.timer);s.timer=setTimeout(()=>listen(s),80);}
async function start(typed=''){if(session||first===second)return;if(!bridge){note('Reload Voice Bridge in Chrome or open the installed Android app.');return;}if(!typed&&bridge.browser&&!(speaker==='auto'?bridge.autoAvailable:speaker==='ja'?(bridge.speechAvailable||bridge.autoAvailable):bridge.speechAvailable)){note('Speech is unavailable in this browser. Open Voice Bridge in Chrome, or type a phrase below.');return;}note();bridge.setAuto?.((speaker==='auto'||(speaker==='ja'&&bridge.japaneseLocal))&&!typed);const s={id:++generation,engine:new TranslationEngine(),phase:'preparing',language:speaker,typed:!!typed};session=s;status('Preparing free translation pack…');render();try{await s.engine.run('prepare',{source:first,target:second,session:s.id},p=>progress(s,p));if(session!==s)return;if(typed){s.phase='listening';await translate(s,typed,speaker==='auto'?(/[\u3040-\u30ff\u3400-\u9fff]/u.test(typed)?'ja':'en'):speaker);}else listen(s);}catch(e){if(session===s){note(e.message);stop('Could not start · check Wi-Fi and free storage');}}}
async function translate(s,words,from){if(session!==s||s.phase!=='listening')return;s.phase='translating';render();status('Translating '+name(from)+' → '+name(from===first?second:first)+'…');$('level').value=0;note();const to=from===first?second:first;$('original-label').textContent=name(from)+' · Original';$('original').textContent=words;$('original').lang=from;$('translation-label').textContent=name(to)+' · Translation';$('translation').textContent='Translating…';try{const result=await s.engine.run('translate',{source:from,target:to,text:words},p=>progress(s,p));if(session!==s)return;$('translation').textContent=result.translation;$('translation').lang=to;$('progress').hidden=true;if($('auto-read').checked){s.phase='speaking';status('Speaking translation · microphone paused');render();s.playbackTimer=setTimeout(()=>{if(session===s){bridge.stopSpeech();note('Playback timed out; showing text.');rearm(s);}},Math.max(20000,result.translation.length*180));bridge.read(result.translation,tags[to]||to,s.id);}else rearm(s);}catch(e){if(session===s){note(e.message);stop('Translation interrupted · tap Start to retry');}}}
window.addEventListener('voice-bridge',({detail:e})=>{const s=session;if(!s||e.id!==s.id)return;if(e.type==='ready')status(e.message||'Listening · '+name(s.language));else if(e.type==='notice'){note(e.message);if(e.fallback&&$('retry-japanese'))$('retry-japanese').hidden=false;}else if(e.type==='speech')status('Hearing '+name(s.language)+' · pause to translate');else if(e.type==='rms')$('level').value=Math.max(0,Math.min(10,e.level));else if(e.type==='partial'&&s.phase==='listening'){$('original-label').textContent=name(s.language)+' · Original';$('original').textContent=e.text;}else if(e.type==='recognizing')status(e.message||'Recognizing '+name(s.language)+'…');else if(e.type==='result')void translate(s,e.text,e.language||s.language);else if(e.type==='empty'){if(s.phase==='listening')rearm(s);}else if(e.type==='error'){note(e.message);stop('Speech interrupted · tap Start to retry');}else if(e.type==='read-end'||e.type==='read-error'){if(s.phase!=='speaking')return;clearTimeout(s.playbackTimer);if(e.type==='read-error')note(e.message);rearm(s);}else if(e.type==='paused')stop('Paused · tap Start when you return');});
if($('speech-details')){const agent=navigator.userAgent||'';const browserName=agent.includes('SamsungBrowser')?'Samsung Internet':agent.includes('EdgA')?'Edge':agent.includes('Chrome')?'Chrome':'this app’s browser';$('speech-details').textContent=browserName+' · '+(bridge.speechAvailable?'browser speech is available; Japanese support is checked when you speak.':'browser speech is not exposed here. Open the official link in Chrome to try faster Japanese.');}
if($('retry-japanese'))$('retry-japanese').onclick=()=>{bridge.setJapaneseMode?.('fast');$('japanese-speech').value='fast';$('retry-japanese').hidden=true;choose('ja');};
if($('japanese-speech'))$('japanese-speech').onchange=()=>{bridge.setJapaneseMode?.($('japanese-speech').value);choose(speaker);};
if($('speaker-auto'))$('speaker-auto').onclick=()=>choose('auto');
function choose(code){speaker=code;note();bridge.setAuto?.(code==='auto'||(code==='ja'&&bridge.japaneseLocal));render();const s=session;if(!s){status(name(code)+' selected · tap Start conversation');return;}clearTimeout(s.timer);if(s.phase==='speaking'){clearTimeout(s.playbackTimer);bridge.stopSpeech();listen(s);}else if(s.phase==='listening'){bridge.stopListening();listen(s);}}
if($('translate-text'))$('translate-text').onclick=()=>{const words=$('typed-text').value.trim();if(!words){note('Type a phrase first.');return;}void start(words);};
$('speaker-first').onclick=()=>choose(first);$('speaker-second').onclick=()=>choose(second);$('start').onclick=()=>session?stop():void start();$('finish').onclick=()=>{if(session?.phase==='listening'){status('Recognizing '+name(session.language)+'…');bridge.finish();}};
$('auto-read').onchange=()=>{if(!$('auto-read').checked&&session?.phase==='speaking'){clearTimeout(session.playbackTimer);bridge.stopSpeech();rearm(session);}};
for(const id of ['first','second'])$(id).onchange=()=>{first=$('first').value;second=$('second').value;speaker=first;note(first===second?'Choose two different languages.':'');render();};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&session)stop('Paused · tap Start when you return');});
window.addEventListener('pagehide',()=>stop());render();
